/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for sm2signature
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder sm2signature_decoder;

extern int sm2_get_signature_r(void *, size_t, unsigned char, const void *, size_t);
extern int sm2_get_signature_s(void *, size_t, unsigned char, const void *, size_t);

